version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  bloat:
    tty: true
    # image: 'bitnami/rails:latest'
    image: 'andresakata/rails-jemalloc:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      # - MALLOC_ARENA_MAX=2
      # - MALLOC_ARENA_MAX=64
      - DATABASE_URL=mysql2://mariadb/app_production
      - RAILS_ENV=production
      - SECRET_KEY_BASE=1
      - PIDFILE=/app/tmp/pids/jemalloc.pid
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
